apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dep-nginx
  name: dep-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dep-nginx
status:
  loadBalancer: {}
#k expose deployment  dep-nginx --port=80 --dry-run -o yaml
